imports:
  - { resource: themes.yml }

debug: false

database:
  driver: pdo_mysql
  user: karambol
  password: ThisIsNotASecret
  dbname: karambol

logger:
  file: ~
  level: WARNING

mailer:
  sender_address: [noreply@karambol.lan, Karambol Mailer]
  options:
    host: 127.0.0.1
    port: 25
    username: ~
    password: ~
    encryption: ~
    auth_mode: ~
  delivery_whitelist: ~
  delivery_addresses: ~

assets:
  jquery:
    - { src: vendor/components/jquery, dest: public/vendor/jquery }
  bootstrap:
    - { src: vendor/twbs/bootstrap/dist, dest: public/vendor/bootstrap }
  font-awesome:
    - { src: vendor/font-awesome/font-awesome/css, dest: public/vendor/font-awesome/css }
    - { src: vendor/font-awesome/font-awesome/fonts, dest: public/vendor/font-awesome/fonts }
  code-mirror:
    - { src: vendor/codemirror/codemirror/lib, dest: public/vendor/codemirror/lib }
    - { src: vendor/codemirror/codemirror/mode, dest: public/vendor/codemirror/mode }
    - { src: vendor/codemirror/codemirror/addon, dest: public/vendor/codemirror/addon }
  debugbar:
    - { src: vendor/maximebf/debugbar/src/DebugBar/Resources, dest: public/vendor/debugbar }
