imports:
  - { resource: assets.yml }
  - { resource: plugins.yml }
  - { resource: '../themes/yeti/config.yml' }

debug: true

database:
  driver: pdo_mysql
  user: karambol
  password: ThisIsNotASecret
  dbname: karambol

theme:
  availableThemes: [yeti]
  defaultTheme: yeti

logger:
  file: ~
  level: debug

entities:
  - src/Entity
